spring:
  application:
    name: core-batch


  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  batch:
    jdbc:
      initialize-schema: ALWAYS

api:
  gateway:
    host: localhost
    port: 8080

eureka:
  instance:
    instance-id: core-batch-api
    hostname: localhost
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:1234@localhost:8761/eureka

schedule:
  user:
    grading:
      cron: 0 0/1 * * * ?
    status:
      cron: 0 0/1 * * * ?
      limit: 3
  order:
    shipped:
      cron: 0 0 12 * * ?

nhncloud:
  keymanager:
    appkey: 2SxwmBzUfnqJaA2A
    mysql:
      url: cacea6422cee4017b8af5edd24834165
      username: 6764281f095b4154ab34a04b4fea6b8d
      password: 3a23273e707b438e94f104f47ce7a7ba
